#!/bin/bash -f
# Copyright (c) 2012, The SAVI Project.
# Eliot J. Kang

# you need to run "source devi/savienvrc <username> <tenantname>"
# before running this file
if [[ -z $1 || -z $2 ]]; then
  echo "Usage: $0 <file> <Service HOST:PORT>"
  exit
fi

# Get TempURL for file
TEMPURL=`get-file $1 1000`
echo $TEMPURL
TEMPURL="tempUrl=$TEMPURL"
curl -s -X POST --data-urlencode "$TEMPURL" http://$2/getSum
