#!/bin/bash -f
# Copyright (c) 2012, The SAVI Project.
# Eliot J. Kang

# you need to run "source devi/savienvrc <username> <tenantname>"
# before running this file
if [[ -z $1 || -z $2 ]]; then
  echo "Usage: $0 <from file> <to file> <Service HOST:PORT>"
  exit
fi

# Get TempURL for from file
FROM=`get-file $1 1000`
# Get TempURL for to file
TO=`put-file $2 1000`
echo "From: $FROM"
echo "To: $TO"
FROM="_from=$1"
TO="_to=$2"
curl -s -X POST --data-urlencode $FROM --data-urlencode $TO http://$3/swapCase
